global:
  resolve_timeout: 5m

route:
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'your_email@example.com'
        from: 'alertmanager@example.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'your_email@example.com'
        auth_identity: 'your_email@example.com'
        auth_password: 'your_app_password'
webhook_configs:
  - url: 'http://host.docker.internal:5001/'
